#test:
# service: Disk
# root: <%= Rails.root.join("tmp/storage") %>
#
#local:
# credentials: <%= Rails.root.join("storage") %>


# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
 amazon:
   service: S3
   access_key_id: ENV.fetch('AWS_ACCESS_KEY_ID')
   secret_access_key: ENV.fetch('AWS_SECRET_ACCESS_KEY')
   region: us-east-1
   bucket: ENV.fetch('AWS_BUCKET')

#Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: fileBase
#   credentials: <%= Rails.root.join("./service_account.json") %>
#   bucket: filebase

# Use rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
